import type { Anomaly } from "@/types/anomaly";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
	page: {
		padding: 30,
		backgroundColor: "#ffffff",
		fontFamily: "Helvetica",
	},
	header: {
		marginBottom: 20,
		borderBottomWidth: 1,
		borderBottomColor: "#cccccc",
		paddingBottom: 10,
	},
	title: {
		fontSize: 24,
		color: "#1e293b",
		fontWeight: "bold",
	},
	subtitle: {
		fontSize: 12,
		color: "#64748b",
		marginTop: 5,
	},
	section: {
		marginBottom: 15,
	},
	sectionTitle: {
		fontSize: 14,
		fontWeight: "bold",
		color: "#334155",
		marginBottom: 8,
		backgroundColor: "#f1f5f9",
		padding: 5,
	},
	text: {
		fontSize: 10,
		marginBottom: 5,
		lineHeight: 1.4,
		color: "#475569",
	},
	table: {
		display: "flex",
		width: "auto",
		borderStyle: "solid",
		borderWidth: 1,
		borderColor: "#e2e8f0",
		marginTop: 10,
	},
	tableRow: {
		flexDirection: "row",
		borderBottomWidth: 1,
		borderBottomColor: "#e2e8f0",
		alignItems: "center",
		height: 24,
	},
	tableHeader: {
		backgroundColor: "#f8fafc",
		color: "#1e293b",
		fontWeight: "bold",
	},
	tableCol: {
		width: "25%",
		borderRightWidth: 1,
		borderRightColor: "#e2e8f0",
		paddingLeft: 5,
	},
	tableCell: {
		fontSize: 9,
		color: "#334155",
	},
	summaryBox: {
		borderWidth: 1,
		borderColor: "#3b82f6",
		backgroundColor: "#eff6ff",
		padding: 10,
		borderRadius: 4,
		marginBottom: 20,
	},
});

interface ReportPDFProps {
	data: Anomaly[];
	summary?: string;
	jobId: string;
}

export const ReportPDF = ({ data, summary, jobId }: ReportPDFProps) => (
	<Document>
		<Page size="A4" style={styles.page}>
			<View style={styles.header}>
				<Text style={styles.title}>Anomaly Detection Report</Text>
				<Text style={styles.subtitle}>
					Job ID: {jobId} | Date: {new Date().toLocaleDateString()}
				</Text>
			</View>

			{summary && (
				<View style={styles.section}>
					<Text style={styles.sectionTitle}>AI Executive Summary</Text>
					<View style={styles.summaryBox}>
						<Text style={styles.text}>{summary}</Text>
					</View>
				</View>
			)}

			<View style={styles.section}>
				<Text style={styles.sectionTitle}>Top Anomalies</Text>
				<View style={styles.table}>
					<View style={[styles.tableRow, styles.tableHeader]}>
						<View style={styles.tableCol}>
							<Text style={styles.tableCell}>Identifier</Text>
						</View>
						<View style={styles.tableCol}>
							<Text style={styles.tableCell}>Amount ($)</Text>
						</View>
						<View style={styles.tableCol}>
							<Text style={styles.tableCell}>Score</Text>
						</View>
						<View style={styles.tableCol}>
							<Text style={styles.tableCell}>Time</Text>
						</View>
					</View>
					{data.slice(0, 20).map((item, i) => (
						<View key={i} style={styles.tableRow}>
							<View style={styles.tableCol}>
								<Text style={styles.tableCell}>{item.identifier}</Text>
							</View>
							<View style={styles.tableCol}>
								<Text style={styles.tableCell}>{item.raw_amount}</Text>
							</View>
							<View style={styles.tableCol}>
								<Text style={styles.tableCell}>
									{item.normalized_distance.toFixed(4)}
								</Text>
							</View>
							<View style={styles.tableCol}>
								<Text style={styles.tableCell}>
									{new Date(item.created_at.value).toLocaleTimeString()}
								</Text>
							</View>
						</View>
					))}
				</View>
			</View>

			<Text style={[styles.text, { marginTop: 20, fontSize: 8, color: "#94a3b8" }]}>
				Generated by Risk Analysis Engine (Gemini 2.5 Flash + BigQuery K-Means)
			</Text>
		</Page>
	</Document>
);
