import { getManualReports } from '@/app/actions/manual-reporting';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { PlusCircle, Search } from 'lucide-react';
import Link from 'next/link';

export default async function ManualScreeningPage() {
  const { data: reports } = await getManualReports();

  return (
    <div className="flex flex-col gap-6 p-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Manual Screening</h1>
          <p className="text-muted-foreground">
            Manage and view manual investigative reports.
          </p>
        </div>
        <Link href="/dashboard/manual-screening/new">
          <Button className="gap-2">
            <PlusCircle className="h-4 w-4" />
            New Report
          </Button>
        </Link>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Recent Reports</CardTitle>
          <CardDescription>
            A list of all manual risk assessment reports generated by analysts.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {!reports || reports.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-10 text-muted-foreground">
              <Search className="h-10 w-10 mb-2 opacity-50" />
              <p>No reports found. Create your first one.</p>
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Client Name</TableHead>
                  <TableHead>Risk Level</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Analyst</TableHead>
                  <TableHead>Created At</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {reports.map((report) => (
                  <TableRow key={report.id}>
                    <TableCell className="font-medium">{report.clientName}</TableCell>
                    <TableCell>
                      <Badge variant={getRiskBadgeVariant(report.riskLevel as any)}>
                        {report.riskLevel}
                      </Badge>
                    </TableCell>
                    <TableCell>
                      <Badge variant="outline" className="capitalize">
                        {report.status.toLowerCase()}
                      </Badge>
                    </TableCell>
                    <TableCell>{report.analystId}</TableCell>
                    <TableCell>{new Date(report.createdAt).toLocaleDateString()}</TableCell>
                    <TableCell className="text-right">
                      <Link href={`/dashboard/manual-screening/${report.id}`}>
                        <Button variant="ghost" size="sm">
                          View
                        </Button>
                      </Link>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

function getRiskBadgeVariant(level: string) {
  switch (level) {
    case 'CRITICAL':
    case 'HIGH':
      return 'destructive';
    case 'MEDIUM':
      return 'secondary'; // using secondary as 'warning' isn't standard in shadcn usually, or default
    case 'LOW':
      return 'default'; // or success if available, default is generic
    default:
      return 'outline';
  }
}
