import { getManualReport } from '@/app/actions/manual-reporting';
import { PrintButton } from '@/components/print-button';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { ChevronLeft } from 'lucide-react';
import Link from 'next/link';
import { notFound } from 'next/navigation';

export default async function ReportViewPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const report = await getManualReport(id);

  if (!report) {
    notFound();
  }

  return (
    <div className="flex flex-col gap-6 p-6 max-w-4xl mx-auto print:p-0 print:max-w-none">
      {/* Header - Hidden in Print */}
      <div className="flex items-center justify-between print:hidden">
        <div className="flex items-center gap-2">
          <Link href="/dashboard/manual-screening">
            <Button variant="ghost" size="icon">
              <ChevronLeft className="h-4 w-4" />
            </Button>
          </Link>
          <h1 className="text-2xl font-bold tracking-tight">Report Details</h1>
        </div>
        <PrintButton />
      </div>

      {/* Printable Report Content */}
      <div className="space-y-6">
        <Card className="print:border-0 print:shadow-none">
          <CardHeader className="border-b print:border-b-2">
            <div className="flex justify-between items-start">
              <div>
                <CardTitle className="text-3xl mb-2">Investigative Report</CardTitle>
                <div className="text-sm text-muted-foreground">
                  Reference: {report.id}
                </div>
              </div>
              <div className="text-right">
                <div className="font-semibold text-lg">{new Date(report.createdAt).toLocaleDateString()}</div>
                <div className="text-sm text-muted-foreground">Generated by System</div>
              </div>
            </div>
          </CardHeader>
          <CardContent className="pt-6 space-y-8">
            {/* Client Info Grid */}
            <div className="grid grid-cols-2 gap-8 p-4 bg-muted/20 rounded-lg print:bg-transparent print:p-0">
              <div>
                <div className="text-sm font-medium text-muted-foreground mb-1">Subject Entity</div>
                <div className="text-xl font-bold">{report.clientName}</div>
              </div>
              <div>
                <div className="text-sm font-medium text-muted-foreground mb-1">Assigned Analyst</div>
                <div className="text-lg">{report.analystId}</div>
              </div>
            </div>

            {/* Risk Assessment */}
            <div>
              <h3 className="text-lg font-semibold mb-3 border-b pb-2">Risk Assessment</h3>
              <div className="flex gap-12 items-center">
                 <div>
                    <div className="text-sm font-medium text-muted-foreground mb-1">Risk Classification</div>
                    <Badge className="text-lg px-4 py-1" variant={report.riskLevel === 'HIGH' || report.riskLevel === 'CRITICAL' ? 'destructive' : 'default'}>
                      {report.riskLevel}
                    </Badge>
                 </div>
                 <div>
                    <div className="text-sm font-medium text-muted-foreground mb-1">Status</div>
                    <div className="capitalize">{report.status.toLowerCase()}</div>
                 </div>
              </div>
            </div>

            {/* Findings */}
            <div>
               <h3 className="text-lg font-semibold mb-3 border-b pb-2">Analyst Findings</h3>
               <div className="prose max-w-none text-gray-700 dark:text-gray-300 whitespace-pre-wrap">
                 {report.findings}
               </div>
            </div>
          </CardContent>
        </Card>

        <div className="hidden print:block text-center text-xs text-muted-foreground mt-10 pt-10 border-t">
           Confidential Risk Management Report &bull; Generated on {new Date().toLocaleDateString()}
        </div>
      </div>
    </div>
  );
}
